# Generated by Django 4.2.7 on 2023-11-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
