# Generated by Django 4.2.7 on 2023-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movie_about_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.CharField(max_length=30),
        ),
    ]
